import type { Metadata } from "next";
import { Inter } from "next/font/google"; // google fonts
import "./globals.css";
import Navbar from "@/components/Navbar"; // @ represent the root director that is src replacement of  ../../ in next.js

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; // it accept the jsx element , that means react formate (due to type script)
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Navbar />

        {children}
      </body>
    </html>
  );
}
